<a href="https://colab.research.google.com/github/karywnl/data-science/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [ ]:
fruits = pd.DataFrame({"Apples" : [30], "Bananas" : [21]})
fruits

   Apples  Bananas
0      30       21

In [ ]:
fruit_sales = pd.DataFrame({"Apples" : [35, 41], "Bannas" : [21, 34]}, index = ["2017 Sales", "2018 Sales"])
fruit_sales

            Apples  Bannas
2017 Sales      35      21
2018 Sales      41      34

In [ ]:
ingredients = pd.Series(["4 cups", "1 cup", "2 large", "1 can"],
                        index = ["Flour", "Milk", "Eggs", "Spam"],
                        name = "Dinner")
ingredients

Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object

In [ ]:
ingredients.to_csv("ingredients.csv")

In [ ]:
import os
from google.colab import drive

drive.mount("/content/drive")
os.environ["KAGGLE_CONFIG_DIR"] = "/content/drive/MyDrive/Kaggle"

!chmod 600 "/content/drive/MyDrive/Kaggle/kaggle.json"

Mounted at /content/drive

In [ ]:
!kaggle datasets download -d zynicide/wine-reviews
!unzip wine-reviews.zip

Dataset URL: https://www.kaggle.com/datasets/zynicide/wine-reviews
License(s): CC-BY-NC-SA-4.0
Downloading wine-reviews.zip to /content
  0% 0.00/50.9M [00:00<?, ?B/s]
100% 50.9M/50.9M [00:00<00:00, 1.74GB/s]
Archive:  wine-reviews.zip
  inflating: winemag-data-130k-v2.csv
  inflating: winemag-data-130k-v2.json
  inflating: winemag-data_first150k.csv

In [ ]:
reviews = pd.read_csv("winemag-data-130k-v2.csv")
reviews.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [ ]:
type(reviews['description'])

pandas.core.series.Series

In [ ]:
first_description = reviews['description'][0]
print(first_description)

Aromas include tropical fruit, broom, brimstone and dried herb. The palate isn't overly expressive, offering unripened apple, citrus and dried sage alongside brisk acidity.

In [ ]:
reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129971 entries, 0 to 129970
Data columns (total 14 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Unnamed: 0             129971 non-null  int64
 1   country                129908 non-null  object
 2   description            129971 non-null  object
 3   designation            92506 non-null   object
 4   points                 129971 non-null  int64
 5   price                  120975 non-null  float64
 6   province               129908 non-null  object
 7   region_1               108724 non-null  object
 8   region_2               50511 non-null   object
 9   taster_name            103727 non-null  object
 10  taster_twitter_handle  98758 non-null   object
 11  title                  129971 non-null  object
 12  variety                129970 non-null  object
 13  winery                 129971 non-null  object
dtypes: float64(1), int64(2), object(11)
memory usage: 13.9+ MB

In [ ]:
reviews.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [ ]:
bargain_wine = reviews[reviews['points'] /reviews['price'] == (reviews['points'] /reviews['price']).max()]['title'].iloc[0]

In [ ]:
reviews.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [ ]:
reviews['description']

0         Aromas include tropical fruit, broom, brimston...
1         This is ripe and fruity, a wine that is smooth...
2         Tart and snappy, the flavors of lime flesh and...
3         Pineapple rind, lemon pith and orange blossom ...
4         Much like the regular bottling from 2012, this...
                                ...
129966    Notes of honeysuckle and cantaloupe sweeten th...
129967    Citation is given as much as a decade of bottl...
129968    Well-drained gravel soil gives this wine its c...
129969    A dry style of Pinot Gris, this is crisp with ...
129970    Big, rich and off-dry, this is powered by inte...
Name: description, Length: 129971, dtype: object

In [ ]:
reviews['description'].iloc[0]

"Aromas include tropical fruit, broom, brimstone and dried herb. The palate isn't overly expressive, offering unripened apple, citrus and dried sage alongside brisk acidity."

In [ ]:
def count(word):
  cnt = 0
  for description in reviews['description']:
    if word in description:
      cnt += 1
  return cnt

count('')

129971

In [ ]:
descriptor_counts = pd.Series(data = {'tropical' : count('tropical'), 'fruity' : count('fruity')})

print(descriptor_counts)

tropical    3607
fruity      9090
dtype: int64

In [ ]:
def star_rate(row):
    if row['country'] == 'Canada':
        return 3
    elif row['points'] >= 95:
        return 3
    elif row['points'] >= 85:
        return 2
    else:
        return 1

row = reviews[['country', 'points']].iloc[65]
print(row)
print(star_rate(row))

country    France
points         86
Name: 65, dtype: object
2

In [ ]:
star_ratings = reviews.apply(star_rate, axis='columns')
print(star_ratings)

0         2
1         2
2         2
3         2
4         2
         ..
129966    2
129967    2
129968    2
129969    2
129970    2
Length: 129971, dtype: int64

.map(): This is a Series method. It’s a specialist. It transforms each individual element in a single column based on a dictionary, a Series, or a function. It doesn't know other columns exist; it only sees the value in front of it. 🎯
 ***It takes input as dict, series, function***

.apply(): It can work on a Series (element-wise) or a DataFrame. When used on a DataFrame, it can look at entire rows or columns at once. This allows it to perform calculations that involve multiple features (e.g., Total = Price * Quantity). 🛠️
***It takes only function input***

In [ ]:
import pandas as pd

df = pd.DataFrame({'Student': ['Miguel', 'Robby', 'Hawk']})
status_map = {'Miguel': 'Champion', 'Robby': 'Finalist', 'Hawk': 'Wildcard'}

# Use .map() to quickly swap names for titles using a dict
df['Status'] = df['Student'].map(status_map)

In [ ]:
df = pd.DataFrame({
    'Hero': ['Cap', 'Spidey', 'Iron Man'],
    'Strength': [100, 80, 70],
    'Agility': [85, 120, 50]
})

# Use .apply() with axis=1 to look at the whole "row" (all columns)
def calc_hero_score(row):
    return (row['Strength'] * 1.5) + row['Agility']

df['Hero_Score'] = df.apply(calc_hero_score, axis=1)

In [ ]:
reviews[['country', 'province']]

         country           province
0          Italy  Sicily & Sardinia
1       Portugal              Douro
2             US             Oregon
3             US           Michigan
4             US             Oregon
...          ...                ...
129966   Germany              Mosel
129967        US             Oregon
129968    France             Alsace
129969    France             Alsace
129970    France             Alsace

[129971 rows x 2 columns]

In [ ]:
reviews.groupby(['country', 'province']).apply(lambda reviews : reviews.loc[reviews['points'].idxmax()])

/tmp/ipython-input-147/646699943.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  reviews.groupby(['country', 'province']).apply(lambda reviews : reviews.loc[reviews['points'].idxmax()])

                            Unnamed: 0    country  \
country   province
Argentina Mendoza Province       82754  Argentina
          Other                  78303  Argentina
Armenia   Armenia                66146    Armenia
Australia Australia Other        37882  Australia
          New South Wales        85337  Australia
...                                ...        ...
Uruguay   Juanico                 9133    Uruguay
          Montevideo             15750    Uruguay
          Progreso               93103    Uruguay
          San Jose               39898    Uruguay
          Uruguay                39361    Uruguay

                                                                  description  \
country   province
Argentina Mendoza Province  If the color doesn't tell the full story, the ...
          Other             Take note, this could be the best wine Colomé ...
Armenia   Armenia           Deep salmon in color, this wine offers a bouqu...
Australia Australia Other   Writes the book on how to make a wine filled w...
          New South Wales   De Bortoli's Noble One is as good as ever in 2...
...                                                                       ...
Uruguay   Juanico           This mature Bordeaux-style blend is earthy on ...
          Montevideo        A rich, heady bouquet offers aromas of blackbe...
          Progreso          Rusty in color but deep and complex in nature,...
          San Jose          Baked, sweet, heavy aromas turn earthy with ti...
          Uruguay           Cherry and berry aromas are ripe, healthy and ...

                                                        designation  points  \
country   province
Argentina Mendoza Province                         Nicasia Vineyard      97
          Other                                             Reserva      95
Armenia   Armenia                                    Estate Bottled      88
Australia Australia Other                             Sarah's Blend      93
          New South Wales                        Noble One Bortytis      94
...                                                             ...     ...
Uruguay   Juanico                  Preludio Barrel Select Lote N 77      90
          Montevideo        Monte Vide Eu Tannat-Merlot-Tempranillo      91
          Progreso                   Etxe Oneko Fortified Sweet Red      90
          San Jose                         El Preciado Gran Reserva      87
          Uruguay                         Blend 002 Limited Edition      91

                            price          province                 region_1  \
country   province
Argentina Mendoza Province  120.0  Mendoza Province                  Mendoza
          Other              90.0             Other                    Salta
Armenia   Armenia            15.0           Armenia                      NaN
Australia Australia Other    15.0   Australia Other  South Eastern Australia
          New South Wales    32.0   New South Wales          New South Wales
...                           ...               ...                      ...
Uruguay   Juanico            45.0           Juanico                      NaN
          Montevideo         60.0        Montevideo                      NaN
          Progreso           46.0          Progreso                      NaN
          San Jose           50.0          San Jose                      NaN
          Uruguay            22.0           Uruguay                      NaN

                           region_2        taster_name taster_twitter_handle  \
country   province
Argentina Mendoza Province      NaN  Michael Schachner           @wineschach
          Other                 NaN  Michael Schachner           @wineschach
Armenia   Armenia               NaN      Mike DeSimone        @worldwineguys
Australia Australia Other       NaN                NaN                   NaN
          New South Wales       NaN     Joe Czerwinski                @JoeCz
...                             ...                ...                   ...
Uruguay   Juanico               NaN  Michael Schachner           @wineschach
          Montevideo            NaN  Michael Schachner           @wineschach
          Progreso              NaN  Michael Schachner           @wineschach
          San Jose              NaN  Michael Schachner           @wineschach
          Uruguay               NaN  Michael Schachner           @wineschach

                                                                        title  \
country   province
Argentina Mendoza Province  Bodega Catena Zapata 2006 Nicasia Vineyard Mal...
          Other                            Colomé 2010 Reserva Malbec (Salta)
Armenia   Armenia                 Van Ardi 2015 Estate Bottled Rosé (Armenia)
Australia Australia Other   Marquis Philips 2000 Sarah's Blend Red (South ...
          New South Wales   De Bortoli 2007 Noble One Bortytis Semillon (N...
...                                                                       ...
Uruguay   Juanico           Familia Deicas 2004 Preludio Barrel Select Lot...
          Montevideo        Bouza 2015 Monte Vide Eu Tannat-Merlot-Tempran...
          Progreso          Pisano 2007 Etxe Oneko Fortified Sweet Red Tan...
          San Jose          Castillo Viejo 2005 El Preciado Gran Reserva R...
          Uruguay           Narbona NV Blend 002 Limited Edition Tannat-Ca...

                                          variety                winery
country   province
Argentina Mendoza Province                 Malbec  Bodega Catena Zapata
          Other                            Malbec                Colomé
Armenia   Armenia                            Rosé              Van Ardi
Australia Australia Other               Red Blend       Marquis Philips
          New South Wales                Sémillon            De Bortoli
...                                           ...                   ...
Uruguay   Juanico                       Red Blend        Familia Deicas
          Montevideo                    Red Blend                 Bouza
          Progreso                         Tannat                Pisano
          San Jose                      Red Blend        Castillo Viejo
          Uruguay           Tannat-Cabernet Franc               Narbona

[425 rows x 14 columns]

In [ ]:
reviews.groupby('country')['price'].min()

country
Argentina                  4.0
Armenia                   14.0
Australia                  5.0
Austria                    7.0
Bosnia and Herzegovina    12.0
Brazil                    10.0
Bulgaria                   8.0
Canada                    12.0
Chile                      5.0
China                     18.0
Croatia                   12.0
Cyprus                    11.0
Czech Republic            15.0
Egypt                      NaN
England                   25.0
France                     5.0
Georgia                    9.0
Germany                    5.0
Greece                     8.0
Hungary                   10.0
India                     10.0
Israel                     8.0
Italy                      5.0
Lebanon                   13.0
Luxembourg                16.0
Macedonia                 15.0
Mexico                     8.0
Moldova                    8.0
Morocco                   14.0
New Zealand                7.0
Peru                      10.0
Portugal                   5.0
Romania                    4.0
Serbia                    15.0
Slovakia                  16.0
Slovenia                   7.0
South Africa               5.0
Spain                      4.0
Switzerland               21.0
Turkey                    14.0
US                         4.0
Ukraine                    6.0
Uruguay                   10.0
Name: price, dtype: float64

In [ ]:
reviews.groupby('country')['price'].agg(min)

/tmp/ipython-input-147/3489987500.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  reviews.groupby('country')['price'].agg(min)

country
Argentina                  4.0
Armenia                   14.0
Australia                  5.0
Austria                    7.0
Bosnia and Herzegovina    12.0
Brazil                    10.0
Bulgaria                   8.0
Canada                    12.0
Chile                      5.0
China                     18.0
Croatia                   12.0
Cyprus                    11.0
Czech Republic            15.0
Egypt                      NaN
England                   25.0
France                     5.0
Georgia                    9.0
Germany                    5.0
Greece                     8.0
Hungary                   10.0
India                     10.0
Israel                     8.0
Italy                      5.0
Lebanon                   13.0
Luxembourg                16.0
Macedonia                 15.0
Mexico                     8.0
Moldova                    8.0
Morocco                   14.0
New Zealand                7.0
Peru                      10.0
Portugal                   5.0
Romania                    4.0
Serbia                    15.0
Slovakia                  16.0
Slovenia                   7.0
South Africa               5.0
Spain                      4.0
Switzerland               21.0
Turkey                    14.0
US                         4.0
Ukraine                    6.0
Uruguay                   10.0
Name: price, dtype: float64

In [ ]:
reviews.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [ ]:
reviews.groupby('taster_twitter_handle')['taster_twitter_handle'].count()

taster_twitter_handle
@AnneInVino          3685
@JoeCz               5147
@bkfiona               27
@gordone_cellars     4177
@kerinokeefe        10776
@laurbuzz            1835
@mattkettmann        6332
@paulgwine           9532
@suskostrzewa        1085
@vboone              9537
@vossroger          25514
@wawinereport        4966
@wineschach         15134
@winewchristina         6
@worldwineguys       1005
Name: taster_twitter_handle, dtype: int64

In [ ]:
reviews['taster_twitter_handle'].value_counts().sort_index()

taster_twitter_handle
@AnneInVino          3685
@JoeCz               5147
@bkfiona               27
@gordone_cellars     4177
@kerinokeefe        10776
@laurbuzz            1835
@mattkettmann        6332
@paulgwine           9532
@suskostrzewa        1085
@vboone              9537
@vossroger          25514
@wawinereport        4966
@wineschach         15134
@winewchristina         6
@worldwineguys       1005
Name: count, dtype: int64

# **GroupBy Exercise**

## 2.
What is the best wine I can buy for a given amount of money? Create a `Series` whose index is wine prices and whose values is the maximum number of points a wine costing that much was given in a review. Sort the values by price, ascending (so that `4.0` dollars is at the top and `3300.0` dollars is at the bottom).

In [ ]:
reviews["points"].loc[reviews["points"].idxmax()]

np.int64(100)

In [ ]:
reviews["points"].max()

100

In [ ]:
reviews.groupby("price")["points"].max()

price
4.0       86
5.0       87
6.0       88
7.0       91
8.0       91
          ..
1900.0    98
2000.0    97
2013.0    91
2500.0    96
3300.0    88
Name: points, Length: 390, dtype: int64

3.
What are the minimum and maximum prices for each variety of wine? Create a DataFrame whose index is the variety category from the dataset and whose values are the min and max values thereof.

In [ ]:
price_extremes = reviews.groupby("variety")['price'].agg(['min', 'max'])

4.
What are the most expensive wine varieties? Create a variable sorted_varieties containing a copy of the dataframe from the previous question where varieties are sorted in descending order based on minimum price, then on maximum price (to break ties).

In [ ]:
sorted_varieties = price_extremes.sort_values(['min', 'max'], ascending=False)

sorted_varieties

                                  min    max
variety
Ramisco                         495.0  495.0
Terrantez                       236.0  236.0
Francisa                        160.0  160.0
Rosenmuskateller                150.0  150.0
Tinta Negra Mole                112.0  112.0
...                               ...    ...
Roscetto                          NaN    NaN
Sauvignon Blanc-Sauvignon Gris    NaN    NaN
Tempranillo-Malbec                NaN    NaN
Vital                             NaN    NaN
Zelen                             NaN    NaN

[707 rows x 2 columns]

5.
Create a Series whose index is reviewers and whose values is the average review score given out by that reviewer. Hint: you will need the taster_name and points columns.

In [ ]:
reviews.groupby("taster_name")["points"].mean()

taster_name
Alexander Peartree    85.855422
Anna Lee C. Iijima    88.415629
Anne Krebiehl MW      90.562551
Carrie Dykes          86.395683
Christina Pickard     87.833333
Fiona Adams           86.888889
Jeff Jenssen          88.319756
Jim Gordon            88.626287
Joe Czerwinski        88.536235
Kerin O’Keefe         88.867947
Lauren Buzzeo         87.739510
Matt Kettmann         90.008686
Michael Schachner     86.907493
Mike DeSimone         89.101167
Paul Gregutt          89.082564
Roger Voss            88.708003
Sean P. Sullivan      88.755739
Susan Kostrzewa       86.609217
Virginie Boone        89.213379
Name: points, dtype: float64

## 6.
What combination of countries and varieties are most common? Create a `Series` whose index is a `MultiIndex`of `{country, variety}` pairs. For example, a pinot noir produced in the US should map to `{"US", "Pinot Noir"}`. Sort the values in the `Series` in descending order based on wine count.

In [ ]:
country_variety_counts = reviews.groupby(["country", "variety"])["winery"].count().sort_values(ascending=False)

country_variety_counts

country    variety
US         Pinot Noir                  9885
           Cabernet Sauvignon          7315
           Chardonnay                  6801
France     Bordeaux-style Red Blend    4725
Italy      Red Blend                   3624
                                       ...
Argentina  Cabernet-Malbec                1
US         Tinta Madeira                  1
Italy      Centesimino                    1
           Catalanesca                    1
           Carmenère                      1
Name: winery, Length: 1612, dtype: int64

# **Data Types and Missing Values**

## 1.
What is the data type of the `points` column in the dataset?

In [ ]:
reviews["points"].dtype

dtype('int64')

## 2.
Create a Series from entries in the `points` column, but convert the entries to strings. Hint: strings are `str` in native Python.

In [ ]:
reviews["points"].astype('str')

0         87
1         87
2         87
3         87
4         87
          ..
129966    90
129967    90
129968    90
129969    90
129970    90
Name: points, Length: 129971, dtype: object

## 3.
Sometimes the price column is null. How many reviews in the dataset are missing a price?

In [ ]:
len(reviews[pd.isnull(reviews["price"])])

129971

## 4.
What are the most common wine-producing regions? Create a Series counting the number of times each value occurs in the `region_1` field. This field is often missing data, so replace missing values with `Unknown`. Sort in descending order.  Your output should look something like this:

```
Unknown                    21247
Napa Valley                 4480
                           ...  
Bardolino Superiore            1
Primitivo del Tarantino        1
Name: region_1, Length: 1230, dtype: int64
```

In [ ]:
reviews["region_1"].fillna("Unknown").value_counts()

region_1
Unknown                               21247
Napa Valley                            4480
Columbia Valley (WA)                   4124
Russian River Valley                   3091
California                             2629
                                      ...
Sonoma-Santa Barbara-Mendocino            1
Sonoma County-Santa Barbara County        1
Del Veneto                                1
Bardolino Superiore                       1
Paestum                                   1
Name: count, Length: 1230, dtype: int64

# **Renaming and Combining**

## 1.
`region_1` and `region_2` are pretty uninformative names for locale columns in the dataset. Create a copy of `reviews` with these columns renamed to `region` and `locale`, respectively.

In [ ]:
reviews.rename(columns={'region_1' : 'region', 'region_2' : 'locale'})

,Unnamed: 0,country,description,designation,points,price,province,region,locale,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

## 2.
Set the index name in the dataset to `wines`.

In [ ]:
reviews.rename_axis("wines", axis='rows')

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
wines,,,,,,,,,,,,,,
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,90,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,129967,US,Citation is given as much as a decade of bottl...,NaN,90,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,129968,France,Well-drained gravel soil gives this wine its c...,Kritt,90,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

## 3.
The [Things on Reddit](https://www.kaggle.com/residentmario/things-on-reddit/data) dataset includes product links from a selection of top-ranked forums ("subreddits") on reddit.com. Run the cell below to load a dataframe of products mentioned on the */r/gaming* subreddit and another dataframe for products mentioned on the *r//movies* subreddit.

In [ ]:
!kaggle datasets download -d residentmario/things-on-reddit
!unzip /content/things-on-reddit.zip -d /content/things-on-reddit/

Streaming output truncated to the last 5000 lines.
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Addons4Kodi.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Adelaide.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Adoption.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AdrenalinePorn.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AdultBreastfeeding.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AdvancedFitness.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AdvancedMicroDevices.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AdvancedProduction.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AdvancedRunning.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AdventureRacing.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Advice.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AdviceAnimals.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Aerials.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AeroPress.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AerospaceEngineering.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Africa.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AfterEffects.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AgainstGamerGate.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AgainstHateSubreddits.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Agnarr.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AirBnB.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AirForce.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AlAnon.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Alabama.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AlanMoore.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AlanWatts.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Albany.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Albuquerque.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AlexisRen.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AliceInChains.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AlienBlue.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AliensAmongUs.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Alienware.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Aliexpress.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Allergies.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AlternativeHistory.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AltonBrown.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Alzheimers.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AmIFreeToGo.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AmISexy.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AmItheAsshole.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Amateur.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AmateurArchives.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AmateurRoomPorn.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AmazingTechnology.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AmazonFlexDrivers.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AmazonMerch.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AmazonSeller.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AmazonTopRated.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AmazonUnder5.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AmazonWTF.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Amd.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AmericanHorrorStory.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Amigurumi.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AmiiboCanada.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AnaheimDucks.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AnalGW.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Anarchism.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Anarcho_Capitalism.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Anarchy101.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AncientCoins.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AncientGreek.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Android.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AndroidGaming.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AndroidMasterRace.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AndroidQuestions.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AndroidTV.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AndroidWear.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Anglicanism.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Angular2.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AnimalCollective.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AnimalCrossing.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AnimalRights.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AnimalShelterStories.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AnimalTextGifs.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AnimalsBeingBros.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AnimalsBeingDerps.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AnimalsBeingJerks.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AnimeDeals.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AnimeFigures.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Animedubs.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Animemes.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Animorphs.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AnnArbor.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Anthropology.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AntiJokes.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Anticonsumption.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Anxiety.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AppalachianTrail.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AppleWatch.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/ApplyingToCollege.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AprilBumpers2018.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AquaSwap.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Aquariums.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Aquascape.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Archaeology.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/ArcherFX.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Archery.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/ArchitecturePorn.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/ArnoldSchwarzenegger.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Arrowheads.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Art.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/ArtCrit.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/ArtFundamentals.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/ArtHistory.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/ArtefactPorn.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/ArtisanVideos.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Asgardia.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Ashens.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AsianBeauty.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AsianBeautyAdvice.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AsianHotties.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AsianMasculinity.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AsianParentStories.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AsiansGoneWild.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AskAShittyMechanic.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AskAcademia.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AskAnAmerican.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AskAnthropology.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AskComputerScience.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AskCulinary.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AskDoctorSmeeee.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AskEconomics.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AskElectronics.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AskEngineers.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AskEurope.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AskFeminists.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AskFoodHistorians.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AskGameMasters.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AskGames.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AskHSteacher.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AskHistorians.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AskHistory.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AskLE.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AskLEO.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AskLiteraryStudies.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AskMen.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AskMenOver30.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AskNYC.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AskNetsec.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AskOuija.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AskParents.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AskPhotography.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AskPhysics.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AskProgramming.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AskReddit.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AskRedditAfterDark.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AskSF.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AskScienceDiscussion.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AskScienceFiction.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AskSocialScience.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AskTechnology.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AskThe_Donald.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AskTrollX.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AskTrumpSupporters.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AskUK.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AskVet.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AskWomen.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AskWomenOver30.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Ask_Politics.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Assistance.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Assyria.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Astronomy.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Astros.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Atari2600.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Atlanta.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AtlantaHawks.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AtlantaTV.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AtlantaUnited.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Atomic_Robo.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AubreyMaturinSeries.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Audi.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AudioPost.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AugustBumpers2017.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AusFinance.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AusSkincare.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Austin.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AustralianCattleDog.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AustralianMakeup.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AustralianPolitics.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Austria.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Authentic_Vaping.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AutoCAD.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AutoDetailing.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AutoImmuneProtocol.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Autocross.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Autoflowers.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Autos.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AvPD.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/AverageBattlestations.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Awwducational.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Axon7.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/Ayahuasca.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/abcjdiscussion.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/abdiscussion.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/ableton.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/abletonlive.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/absolutelynotme_irl.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/abv.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/academiceconomics.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/accelworld.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/acecombat.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/achappyhome.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/acting.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/actualconspiracies.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/actuallesbians.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/actuary.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/ada.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/adderall.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/admincraft.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/adorableporn.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/ads.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/adultery.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/adultswim.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/adventism.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/adventuretime.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/advertising.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/aerospace.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/againstmensrights.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/ageofsigmar.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/aggies.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/agile.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/agnostic.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/aikido.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/ainbow.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/aion.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/airguns.csv
  inflating: /content/things-on-reddit/top-things/top-things/reddits/a/airpods.csv

In [ ]:
gaming_products = pd.read_csv("/content/things-on-reddit/top-things/reddits/g/gaming.csv")
gaming_products['subreddit'] = "r/gaming"
movie_products = pd.read_csv("/content/things-on-reddit/top-things/reddits/m/movies.csv")
movie_products['subreddit'] = "r/movies"

In [ ]:
pd.concat([gaming_products, movie_products])

,name,category,amazon_link,total_mentions,subreddit_mentions,subreddit
0,BOOMco Halo Covenant Needler Blaster,Toys & Games,https://www.amazon.com/BOOMco-Halo-Covenant-Ne...,4.0,4,r/gaming
1,Raspberry PI 3 Model B 1.2GHz 64-bit quad-core...,Electronics,https://www.amazon.com/Raspberry-Model-A1-2GHz...,19.0,3,r/gaming
2,CanaKit 5V 2.5A Raspberry Pi 3 Power Supply / ...,Electronics,https://www.amazon.com/CanaKit-Raspberry-Suppl...,7.0,3,r/gaming
3,Panasonic K-KJ17MCA4BA Advanced Individual Cel...,Electronics,https://www.amazon.com/Panasonic-Advanced-Indi...,29.0,2,r/gaming
4,Mayflash GameCube Controller Adapter for Wii U...,Electronics,https://www.amazon.com/GameCube-Controller-Ada...,24.0,2,r/gaming
...,...,...,...,...,...,...
298,Welcome to Night Vale CD: A Novel,Books,https://www.amazon.com/Welcome-Night-Vale-CD-N...,1.0,1,r/movies
299,Ran (StudioCanal Collection) [Blu-ray],Movies & TV,https://www.amazon.com/StudioCanal-Collection-...,1.0,1,r/movies
300,The Art of John Alvin,Books,https://www.amazon.com/Art-John-Alvin-Andrea/d...,1.0,1,r/movies
301,Apocalypto [Blu-ray],Movies & TV,https://www.amazon.com/Apocalypto-Blu-ray-Rudy...,1.0,1,r/movies
302,Cinelinx: A Card Game for People Who Love Movi...,Toys & Games,https://www.amazon.com/Cinelinx-Card-Game-Peop...,1.0,1,r/movies