<a href="https://colab.research.google.com/github/karywnl/kaggle-learn/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
fruits = pd.DataFrame({"Apples" : [30], "Bananas" : [21]})
fruits

   Apples  Bananas
0      30       21

In [ ]:
fruit_sales = pd.DataFrame({"Apples" : [35, 41], "Bannas" : [21, 34]}, index = ["2017 Sales", "2018 Sales"])
fruit_sales

            Apples  Bannas
2017 Sales      35      21
2018 Sales      41      34

In [ ]:
ingredients = pd.Series(["4 cups", "1 cup", "2 large", "1 can"],
                        index = ["Flour", "Milk", "Eggs", "Spam"],
                        name = "Dinner")
ingredients

Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object

In [ ]:
ingredients.to_csv("ingredients.csv")

In [ ]:
import os
from google.colab import drive

drive.mount("/content/drive")
os.environ["KAGGLE_CONFIG_DIR"] = "/content/drive/MyDrive/Kaggle"

!chmod 600 "/content/drive/MyDrive/Kaggle/kaggle.json"

Mounted at /content/drive

In [ ]:
!kaggle datasets download -d zynicide/wine-reviews
!unzip wine-reviews.zip

Dataset URL: https://www.kaggle.com/datasets/zynicide/wine-reviews
License(s): CC-BY-NC-SA-4.0
Downloading wine-reviews.zip to /content
  0% 0.00/50.9M [00:00<?, ?B/s]
100% 50.9M/50.9M [00:00<00:00, 974MB/s]
Archive:  wine-reviews.zip
  inflating: winemag-data-130k-v2.csv
  inflating: winemag-data-130k-v2.json
  inflating: winemag-data_first150k.csv

In [ ]:
reviews = pd.read_csv("winemag-data-130k-v2.csv")
reviews.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [ ]:
type(reviews['description'])

pandas.core.series.Series

In [ ]:
first_description = reviews['description'][0]
print(first_description)

Aromas include tropical fruit, broom, brimstone and dried herb. The palate isn't overly expressive, offering unripened apple, citrus and dried sage alongside brisk acidity.

In [ ]:
reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129971 entries, 0 to 129970
Data columns (total 14 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Unnamed: 0             129971 non-null  int64
 1   country                129908 non-null  object
 2   description            129971 non-null  object
 3   designation            92506 non-null   object
 4   points                 129971 non-null  int64
 5   price                  120975 non-null  float64
 6   province               129908 non-null  object
 7   region_1               108724 non-null  object
 8   region_2               50511 non-null   object
 9   taster_name            103727 non-null  object
 10  taster_twitter_handle  98758 non-null   object
 11  title                  129971 non-null  object
 12  variety                129970 non-null  object
 13  winery                 129971 non-null  object
dtypes: float64(1), int64(2), object(11)
memory usage: 13.9+ MB

In [ ]:
reviews.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [ ]:
bargain_wine = reviews[reviews['points'] /reviews['price'] == (reviews['points'] /reviews['price']).max()]['title'].iloc[0]

In [ ]:
reviews.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [ ]:
reviews['description']

0         Aromas include tropical fruit, broom, brimston...
1         This is ripe and fruity, a wine that is smooth...
2         Tart and snappy, the flavors of lime flesh and...
3         Pineapple rind, lemon pith and orange blossom ...
4         Much like the regular bottling from 2012, this...
                                ...
129966    Notes of honeysuckle and cantaloupe sweeten th...
129967    Citation is given as much as a decade of bottl...
129968    Well-drained gravel soil gives this wine its c...
129969    A dry style of Pinot Gris, this is crisp with ...
129970    Big, rich and off-dry, this is powered by inte...
Name: description, Length: 129971, dtype: object

In [ ]:
reviews['description'].iloc[0]

"Aromas include tropical fruit, broom, brimstone and dried herb. The palate isn't overly expressive, offering unripened apple, citrus and dried sage alongside brisk acidity."

In [ ]:
def count(word):
  cnt = 0
  for description in reviews['description']:
    if word in description:
      cnt += 1
  return cnt

count('')

129971

In [ ]:
descriptor_counts = pd.Series(data = {'tropical' : count('tropical'), 'fruity' : count('fruity')})

print(descriptor_counts)

tropical    3607
fruity      9090
dtype: int64

In [ ]:
def star_rate(row):
    if row['country'] == 'Canada':
        return 3
    elif row['points'] >= 95:
        return 3
    elif row['points'] >= 85:
        return 2
    else:
        return 1

row = reviews[['country', 'points']].iloc[65]
print(row)
print(star_rate(row))

country    France
points         86
Name: 65, dtype: object
2

In [ ]:
star_ratings = reviews.apply(star_rate, axis='columns')
print(star_ratings)

0         2
1         2
2         2
3         2
4         2
         ..
129966    2
129967    2
129968    2
129969    2
129970    2
Length: 129971, dtype: int64

.map(): This is a Series method. It’s a specialist. It transforms each individual element in a single column based on a dictionary, a Series, or a function. It doesn't know other columns exist; it only sees the value in front of it. 🎯
 ***It takes input as dict, series, function***

.apply(): It can work on a Series (element-wise) or a DataFrame. When used on a DataFrame, it can look at entire rows or columns at once. This allows it to perform calculations that involve multiple features (e.g., Total = Price * Quantity). 🛠️
***It takes only function input***

In [ ]:
import pandas as pd

df = pd.DataFrame({'Student': ['Miguel', 'Robby', 'Hawk']})
status_map = {'Miguel': 'Champion', 'Robby': 'Finalist', 'Hawk': 'Wildcard'}

# Use .map() to quickly swap names for titles using a dict
df['Status'] = df['Student'].map(status_map)

In [ ]:
df = pd.DataFrame({
    'Hero': ['Cap', 'Spidey', 'Iron Man'],
    'Strength': [100, 80, 70],
    'Agility': [85, 120, 50]
})

# Use .apply() with axis=1 to look at the whole "row" (all columns)
def calc_hero_score(row):
    return (row['Strength'] * 1.5) + row['Agility']

df['Hero_Score'] = df.apply(calc_hero_score, axis=1)

345